In [12]:
import geopandas as gpd
import pandas as pd
import shapely
import copy
import os
python_directory = os.getcwd()

# Clean geogson file (remove null)

In [25]:
greens = gpd.read_file(rf"{python_directory}/port_meadow_green.geojson")
greens.fillna("")
greens.to_file(rf"{python_directory}/port_meadow_green.geojson", driver="GeoJSON")

In [15]:
paths = gpd.read_file(rf"{python_directory}/port_meadow_paths.geojson")
greens = gpd.read_file(rf"{python_directory}/port_meadow_boundary_27700.geojson")
entry_points = gpd.read_file(rf"{python_directory}/port_meadow_points.geojson")

---
# Extract nodes and links: Paths
## Example
An example for extracting the nodes:
1. Extract the x and y values from the paths geometry
2. Loop through the extracted x and y values and append the x, y, xy tuples and ids to new lists. The xy tupes are necessary to check if any points are repeated. This can occur when checking other multistrings in case of node intersections
3. Generate a pandas DataFrame listing the nodes and their coordinates

In [16]:
path = paths["geometry"][0]
print(paths["geometry"][0])

# Extract x and y coordinates of the nodes in each line in sequence
x,y = path.geoms[0].xy
x = [round(e, 5) for e in x]
y = [round(e, 5) for e in y]
xy = list(zip(x,y))
print(xy)

# Extract x and y coordinates of the entry points
xy_entry = []
for point in entry_points["geometry"]:
    x_temp, y_temp = point.xy
    xy_entry.append((x_temp[0], y_temp[0]))
print(xy_entry)

# Initialise the lists to captrure the nodes and paths properties
# nodes
xy_list = []
x_list = []
y_list = []
n_id_list = []
n_entry_list = []
# links
l_id_list = []
l_start_list = []
l_end_list = []
max_speed_list = []

n_id_counter = 0
l_id_counter = 0
# Iterate through the nodes indices
for i in range(len(x)):
    #-----------------
    # Nodes
    #-----------------
    # Check if the node has already been given an id
    if (x[i], y[i]) not in xy_list:
        # Identify entry points
        if (x[i], y[i]) in xy_entry: n_entry_list.append(1)
        else: n_entry_list.append(-1)
        # Append relevant parameters
        xy_list.append((x[i], y[i]))
        x_list.append(x[i])
        y_list.append(y[i])
        n_id_list.append(f"n_id{n_id_counter}")
        n_id_counter += 1
    #-----------------
    # Links
    #-----------------
    if i > 0:
        # Find the indices of the nodes in the full xy_lists (including previous geometries)
        i_start = xy_list.index((x[i - 1], y[i - 1]))
        i_end = xy_list.index((x[i], y[i]))
        if i_start == i_end: continue
        # Append the links
        l_start_list.append(n_id_list[i_start])
        l_end_list.append(n_id_list[i_end])
        l_id_list.append(f"l_id{l_id_counter}")
        max_speed_list.append(0)
        l_id_counter += 1

df_dict_nodes = {
        "id": n_id_list,
        "xpos": x_list,
        "ypos": y_list,
        "entry": n_entry_list
    }
df_dict_links = {
    "id": l_id_list,
    "start": l_start_list,
    "end": l_end_list
}
df_nodes = pd.DataFrame(df_dict_nodes)
df_links = pd.DataFrame(df_dict_links)
display(df_nodes)
display(df_links)

MULTILINESTRING ((448974.6973153275 209549.73660843726, 448982.3232377847 209544.78151658943, 448986.44755737705 209541.01583348334, 448999.8964256131 209529.89810240822, 449012.80733911967 209519.67696254884, 449024.6423431674 209509.81445917574, 449037.91189316026 209499.59331931637, 449046.87780531764 209492.7792260768, 449054.4091715298 209483.09604094684, 449058.6960510834 209471.9176731328))
[(448974.69732, 209549.73661), (448982.32324, 209544.78152), (448986.44756, 209541.01583), (448999.89643, 209529.8981), (449012.80734, 209519.67696), (449024.64234, 209509.81446), (449037.91189, 209499.59332), (449046.87781, 209492.77923), (449054.40917, 209483.09604), (449058.69605, 209471.91767)]
[(449100.8007841008, 209625.91316479765), (449865.5697127742, 207343.84408132924), (450222.45993505896, 207832.8085025841), (449392.62681867473, 209977.19481771026), (449393.11971142964, 209976.8528208944), (449396.46716219984, 209974.53034251207), (449398.1742370755, 209973.34595353348), (449854.8579751864, 207291.46669264528), (450080.37429664936, 206990.74571389204), (449569.81232987053, 209673.1965252384), (449536.6544462647, 209600.61964821897), (448599.5449779812, 205094.2285169849), (448577.6354541221, 205076.23226383456), (448537.07186715305, 205043.4747456722), (449490.9153414556, 205491.09576503973), (449503.4877424249, 205462.06086719682), (452149.37249336625, 204711.58941630897), (450476.0406831457, 207899.57310590748), (450475.2250702208, 207889.10560618172), (450474.7554746713, 207887.40313995758), (452700.17961514374, 207639.2911262965), (452607.90163097053, 207584.37043189327), (453035.4910733717, 206638.11464697472), (453035.415274708, 206638.08024771954), (453031.7346395855, 206636.40888402332), (453030.4003631089, 206635.80299719132), (453029.8420729511, 206635.54950270493), (453027.8931073146, 206634.66442195355), (453026.0568396951, 206633.83054009802), (453025.38565153163, 206633.52574673464), (453007.49457511713, 206630.36182493926), (452999.15582760354, 206629.91344097973), (452998.16974563577, 206629.86044287903), (452972.89520786644, 206628.5014916166), (451214.1638407216, 210140.59435166477), (451417.0596750288, 208649.9904058164), (452929.9297822662, 208416.5724115909), (452941.1646543604, 208412.1907415567), (452960.5863616699, 208405.2032548082), (453021.5752735531, 208753.33312737342), (453013.9919052452, 208746.7866048342), (448402.3077434644, 210216.6503895205), (448619.3463571588, 210139.59004622186), (448149.31606998894, 205803.0192941081), (447756.6463126415, 204574.19861281908), (447800.2910264142, 210511.89372428902), (452857.5075594695, 206022.5007077821), (452516.0543650769, 206195.42839232017), (452914.5768594622, 206277.33535726357), (452712.38077089953, 206296.41568314843), (452906.42704738304, 206298.55495578918), (452693.811141067, 206304.6855824429), (452678.9016273475, 206426.5531867675), (452873.33817096305, 206623.14850103646), (452681.4819536214, 206656.83854941168), (452852.7686512115, 206676.4475003496), (452842.5390804751, 206828.16447056667), (453054.4352196762, 206877.10319307767), (452698.45228471153, 207006.79150807043), (452931.17199042527, 208430.7941560258), (452931.19199003687, 208430.79415611288), (452953.65172953135, 208507.88284657086), (452979.62097675493, 208398.35496302793), (452996.7815568847, 208798.9677653351), (453016.5969420729, 207232.09650797438), (453021.2867135524, 207188.98731022346), (453042.49972345267, 208383.84549902723), (451639.84802675195, 205228.80116739753), (451146.04766732384, 205272.66165140667), (452426.2035182604, 205276.43711723393), (452403.58398048073, 205290.5769266605), (452509.03207254666, 205306.48617361888), (452364.3049757413, 205377.5953357626), (452512.88261419046, 205513.30202543153), (452512.8526152839, 205513.48202195112), (452507.48279573175, 205540.491503014), (452513.6627410802, 205561.09106766892), (452513.0727561518, 205562.45104275935), (452443.5543103575, 205646.4296248447), (452258.37810464564, 205747.32827306644), (452302.12735746126, 205772.4176074881), (450825.13569567347, 205852.43144832144), (451420.3043674004, 205858.50905892614), (451496.632926733, 205862.81868125137), (451561.3818051885, 205896.0177565944), (451561.3518057608, 205896.01775670983), (451464.7136531232, 205897.7580946216), (451450.7039341001, 205901.91806458845), (451577.2616809574, 205948.43662275083), (452132.0212386874, 205981.3839587248), (451410.0849825364, 205983.63657319907), (451410.08498260356, 205983.65657279547), (451189.70925819245, 206008.23697255633), (451216.47876983136, 206016.28670562687), (451172.87963811087, 206034.79652281717), (451399.67534346523, 206042.2854533638), (451399.6753435087, 206042.3054529715), (451505.973341113, 206050.40486306342), (452731.81676875445, 208903.385625234), (451143.2572787113, 208958.42953993718), (452515.8010348596, 209016.0640685102), (452509.18121274747, 209038.723648609), (452432.9130751259, 209217.99039265036), (450825.104449539, 209230.73530902248), (452417.50348933355, 209268.48945734015), (450807.33505045355, 209317.16367031023), (451138.9799122993, 209876.3915969247), (451135.6202848448, 210012.34898695408), (451113.21074936766, 210023.14885408082), (451107.8208597309, 210025.1688332492), (451131.9304554985, 210056.0081575503), (451131.76045896683, 210056.0681569653), (451142.14028862026, 210070.7578388984), (451182.7495532538, 210096.92719829682), (451121.5308048271, 210121.01693887508), (451101.8813868891, 210210.43528004526), (450942.474522011, 210228.25546739704), (450928.8048952528, 210281.38448676968), (450919.15521082823, 210345.1532870406), (450978.5940733225, 210349.5530051262), (451298.86790341465, 210352.85188147397), (450985.2341122975, 210429.4214411556), (450950.4648488218, 210462.98090778652), (450966.7545458898, 210467.4407679949), (451085.1423590809, 210504.46966383926), (451042.4433187772, 210570.95852107805), (450701.55982395104, 210578.18949882506), (450733.2592414457, 210589.67917254905), (450917.30579430924, 210616.5380506509), (451252.8106992378, 207145.3845415403), (450970.1662250062, 207219.6541025006), (452900.1892325751, 207270.86570022942), (451185.40238965244, 207282.7820833932), (452853.7802896402, 207313.4150815332), (452524.76716996176, 207440.75398432644), (452318.2112926284, 207464.41435884545), (451555.0962284759, 207520.42619352165), (450888.2486840596, 207524.09830077481), (450908.8083273168, 207532.95805643575), (450867.3091393322, 207545.37794255378), (452607.26604438154, 207584.66092890617), (452195.1342054302, 207616.4519597987), (452594.0864355286, 207623.970236281), (452700.0844162806, 207639.07953068241), (452614.07611735584, 207645.24975398445), (451180.0348362225, 208147.34516510327), (450669.5751922623, 208374.39243780146), (452781.18472808326, 208379.8053179538), (452712.3360929034, 208410.73497106833), (452769.3453395744, 208562.30194884405), (452855.86392181425, 208651.90000811446), (452688.6271394711, 208705.50951857388), (451084.96783448383, 208725.15430472296), (450984.4200686057, 208816.85288396507), (450981.01017196267, 208828.97265799972), (451600.0977167123, 208832.71038118954), (452718.39687705936, 208841.8368540777), (450997.4198787958, 208841.99234373943), (451041.8190203446, 208854.3719425004), (451172.1164895082, 208886.3108524073), (451434.6347326068, 206066.7548354654), (452392.1365532845, 206095.50080560794), (452414.8261911051, 206134.1699601842), (452068.1528334566, 206143.14096935285), (450640.9699789206, 206150.02643713437), (451690.9500585247, 206153.63210914162), (452001.0641542246, 206161.24084569525), (451871.41761399264, 206607.90260106663), (451982.1354677997, 206610.75212463964), (451979.56552487577, 206614.12206852477), (451921.4068076793, 206684.81091096834), (452400.5075487039, 206726.9982268921), (451739.67047700303, 206747.28040399094), (451739.6604772367, 206747.30040364043), (451739.6504776286, 206747.3904019388), (451735.22063196305, 206778.78981065855), (451735.16063365655, 206779.03980604938), (451735.1506339578, 206779.08980511752), (451994.595658152, 206816.81804587675), (452030.7249877971, 206834.70755226247), (451385.2973443881, 206836.92005880852), (451892.8777012717, 206840.51798710768), (450735.05975435965, 206926.34087012417), (451136.75233030313, 206969.48844426917), (451119.28272075945, 206989.61811398), (451160.7419720395, 206999.27776341967), (451819.16959601635, 207012.3049679803), (451879.88848013, 207036.38426270545), (451340.828790145, 207062.9258273751), (451571.3445121212, 207077.7746702297), (452017.2159520554, 207088.84270747472), (450074.2052599396, 207845.6345673495), (450101.84080839506, 206374.90410345874), (450107.55045709613, 206271.37611909903), (450117.4403037169, 206287.11577127082), (450119.20025950926, 206282.64585245698), (450137.22969175136, 206186.91766646766), (450170.62337495724, 207843.26427326375), (450200.7385948257, 206239.44638802204), (450230.53358870547, 208400.03364122042), (450249.43019161536, 207273.08562778257), (450257.1275050498, 206235.83624150924), (450288.23363848927, 208842.61504309863), (450288.6036533936, 208850.50488331896), (450297.5934324021, 208830.33525020885), (450317.44309214375, 208839.44498470775), (450340.1826755417, 208840.1448757529), (450377.99942457885, 207875.67290697084), (450378.6218136657, 208784.4058276246), (450441.4682438134, 207895.54230595496), (450443.1880279396, 207830.39356798586), (450446.3580468221, 207857.98299570446), (450448.9038251034, 206234.86552122125), (450450.98313646566, 205948.24109235842), (450463.6977897357, 207887.44237882947), (450467.2377565572, 207900.45212094922), (450475.04756778205, 207886.9623472229), (450475.11095081666, 209112.35890977381), (450485.7707105818, 209096.35918580816), (450548.82871059584, 208795.60488504887), (450568.96135253954, 206150.23671627138), (450575.55354457913, 207186.26620501617), (448415.98460456135, 209282.18526374723), (448688.1709742762, 209408.79118146206), (448735.9403482714, 209428.39050555893), (449058.6960510834, 209471.9176731328), (449643.9872000523, 209491.47425662045), (449108.5054449552, 209505.18668860284), (448974.6973153275, 209549.73660843726), (449491.67019986885, 209574.4130464805), (449552.5592241672, 209626.88174742), (448873.34886616055, 209684.45453263092), (449536.2497735187, 209718.28993023862), (449156.4752979459, 209732.23179193307), (449684.82737689477, 209818.02758162748), (449656.7879022005, 209820.53762784816), (449705.96705365693, 209839.1371161886), (449665.8878122137, 209844.6871461519), (449440.33234258834, 209944.09605866863), (448771.64071362413, 209988.64949257462), (448757.3409023718, 209997.52941851487), (450025.742629773, 210410.4952150071), (450027.2926014414, 210411.1951959203), (450083.84156710183, 210437.45448477747), (450114.73099967296, 210451.66409799358), (450121.0008851524, 210454.89401282824), (450073.17198817915, 210522.79290279275), (450059.4223224182, 210548.31247056276), (450304.54750627757, 210551.2714718795), (450315.5774924473, 210648.9695449671), (450102.01181624515, 210707.32922372263), (450009.27367449127, 210730.39913544524), (447497.0218714038, 208857.27059498488), (447513.881735782, 208787.36180543067), (447565.07048644, 205693.64916826837), (447572.2304922983, 206176.83006931964), (447584.2702714172, 205679.19930127135), (447585.7003558853, 206176.81996263465), (447979.76636341953, 206078.05861685646), (448099.44516249176, 206252.50452773413), (448103.3951204659, 206237.18477207847), (448117.5649638733, 206154.69614355994), (448193.8942192939, 206273.6134016171), (448205.5541110536, 206304.84274839674), (448903.8224697279, 206147.59282201756), (448960.95067725563, 205680.31170209026), (448969.18118713284, 206079.71390277933), (448986.1110107764, 206152.38246985374), (449102.8184722949, 205910.9367543409), (449521.91183060827, 206315.5475028836), (449562.72199646785, 206667.85037306562), (449578.1200567494, 206059.16235965135), (449650.94875946315, 206093.77139114717), (449656.12871197524, 206113.2009868176), (449700.23763596604, 206024.12257563393), (449703.2072049547, 205848.83591555047), (449718.0773065814, 206028.11242708244), (449740.52685329557, 206018.2125349436), (449769.2264181477, 206061.52156748658), (449825.72533153277, 206057.9014186507), (449972.62326478417, 206360.43488376273), (450028.8513958734, 206031.5311463112), (450032.61134784867, 206041.4009372575), (447476.36209857365, 208573.6461583572), (452515.1425182816, 205495.17237883003), (452515.1425184296, 205495.22237783158), (452519.14101642725, 204644.97864219657), (452533.61165548995, 205319.66580956668), (452557.601200069, 205316.19578051305), (452570.84089123073, 205294.62615590484), (452587.1005114437, 205267.78662303992), (452598.6511475352, 205560.29075804783), (452798.61565656104, 204354.682933665), (453018.66338268464, 205613.30822215305), (453068.41242338583, 205611.6981200223), (453078.93220438994, 205605.41821420303), (453079.1317711563, 205447.44129297388), (452065.72926792613, 204302.70664110885), (451519.7296625629, 204314.47837686463), (452264.4055781542, 204321.85554791905), (452391.333237613, 204363.99429958704), (452401.4730512059, 204368.19418425916), (451501.40004444204, 204415.32660809986), (451805.2941627991, 204434.8552596192), (451716.275947814, 204668.61137354956), (452148.55790866166, 204712.09891038242), (451381.6424404498, 204738.56108879286), (451394.40219680034, 204752.9207896549), (451407.2119514866, 204763.61055774876), (451438.47135330667, 204790.20998376556), (451418.52175423957, 204859.77877175342), (451245.64510350826, 204931.99791771622), (451545.8593158007, 204934.75706409186), (451339.9832858397, 204938.47754649218), (451563.868975562, 204961.2065379428), (452483.77188545186, 205039.51152703527), (452483.7518858797, 205039.6215250978), (452411.90321691084, 205056.69152165652), (452465.9522281251, 205067.04109770822), (450967.6104766427, 205069.14609274134), (452479.42198419844, 205074.1409087823), (451540.1395079118, 205100.46405228245), (451915.2724277337, 205109.81267149956), (451102.67812184134, 205157.2540382262), (451497.2806515375, 205194.3222549731), (451554.0395627031, 205195.25208482234), (451917.6526782757, 205197.05086098134), (451207.7462785756, 205211.38269113068), (450951.6954533571, 203897.81374975137), (451833.1853463122, 204069.11007996136), (451845.0954340971, 204052.76005075738), (451874.1855350508, 204018.72997496766), (451894.0042452245, 204067.56985333515), (447461.0830277515, 204268.7946908914), (447482.21271034837, 204279.6244072009), (447540.22072732734, 205651.04016871646), (448385.49045190355, 205182.69366208615), (448385.520451351, 205182.69366196857), (448404.1201092759, 205182.78358913254), (448429.6796327182, 205178.5435772987), (448430.59963763197, 205193.24327649054), (448465.62899054174, 205191.43317969533), (448465.93909428833, 205264.6217013076), (448520.52795919933, 205177.2532559468), (448596.19643262925, 205089.6347221585), (448669.6950053715, 205008.7259342795), (448722.87389874563, 204771.4199348524), (448947.30089204776, 205659.1621616786), (449228.36574983795, 205653.80134370364), (449231.7356799416, 205648.91142704582), (449511.7701831502, 205464.043996113), (449706.67575258715, 205171.28877340705), (449904.5018072736, 205177.877842339), (449979.3201384752, 205105.5589077617), (450024.8688671016, 204343.4329666379), (450062.28811077756, 204285.6539135874), (450121.36694293015, 204257.43423430616), (450121.37694273173, 204257.42423445982), (450176.515840004, 204180.75548120402), (450232.40516083245, 204123.51601718512)]

      id          xpos          ypos  entry
0  n_id0  448974.69732  209549.73661     -1
1  n_id1  448982.32324  209544.78152     -1
2  n_id2  448986.44756  209541.01583     -1
3  n_id3  448999.89643  209529.89810     -1
4  n_id4  449012.80734  209519.67696     -1
5  n_id5  449024.64234  209509.81446     -1
6  n_id6  449037.91189  209499.59332     -1
7  n_id7  449046.87781  209492.77923     -1
8  n_id8  449054.40917  209483.09604     -1
9  n_id9  449058.69605  209471.91767     -1

      id  start    end
0  l_id0  n_id0  n_id1
1  l_id1  n_id1  n_id2
2  l_id2  n_id2  n_id3
3  l_id3  n_id3  n_id4
4  l_id4  n_id4  n_id5
5  l_id5  n_id5  n_id6
6  l_id6  n_id6  n_id7
7  l_id7  n_id7  n_id8
8  l_id8  n_id8  n_id9

In [17]:
def extract_nodes_links(paths, entry_points) -> pd.DataFrame:
    """
    Extracts the nodes from a geopandas Multistring dataframe.

    Parameters
    ----------
    - `paths`: geopandas DataFrame
        The geopandas dataframe including lines representing paths inside a green space

    Returns
    -------
    - geopandas Dataframe including the node points and their ids
    """
    # Extract x and y coordinates of the entry points
    xy_entry = []
    for point in entry_points["geometry"]:
        x_temp, y_temp = point.xy
        x_temp = [round(e, 5) for e in x_temp]
        y_temp = [round(e, 5) for e in y_temp]
        xy_entry.append((x_temp[0], y_temp[0]))
    print(xy_entry)

    # Initialise the lists to captrure the nodes and paths properties
    xy_list = []
    x_list = []
    y_list = []
    n_id_list = []
    n_sp_list = []
    n_entry_list = []
    l_id_list = []
    l_start_list = []
    l_end_list = []
    max_speed_list = []
    
    n_id_counter = 0
    l_id_counter = 0
    for path in paths["geometry"]:
        x,y = path.geoms[0].xy
        x = [round(e, 5) for e in x]
        y = [round(e, 5) for e in y]
        # Iterate through the nodes indices
        for i in range(len(x)):
            #-----------------
            # Nodes
            #-----------------
            # Check if the node has already been given an id
            if (x[i], y[i]) not in xy_list:
                xy_list.append((x[i], y[i]))
                x_list.append(x[i])
                y_list.append(y[i])
                n_id_list.append(f"n_id{n_id_counter}")
                n_sp_list.append(-1)
                n_id_counter += 1
                # Identify entry points
                if (x[i], y[i]) in xy_entry: n_entry_list.append(1)
                else: n_entry_list.append(-1)
            #-----------------
            # Links
            #-----------------
            if i > 0:
                # Find the indices of the nodes in the full xy_lists (including previous geometries)
                i_start = xy_list.index((x[i - 1], y[i - 1]))
                i_end = xy_list.index((x[i], y[i]))
                if i_start == i_end: continue
                # Append the links
                l_start_list.append(n_id_list[i_start])
                l_end_list.append(n_id_list[i_end])
                l_id_list.append(f"l_id{l_id_counter}")
                max_speed_list.append(0)
                l_id_counter += 1

    df_dict_nodes = {
        "id": n_id_list,
        "xpos": x_list,
        "ypos": y_list,
        "sp_id": n_sp_list,
        "entry": n_entry_list
    }
    df_dict_links = {
        "id": l_id_list,
        "start": l_start_list,
        "end": l_end_list,
        "maxspeed": max_speed_list
    }
    df_nodes = pd.DataFrame(df_dict_nodes)
    df_links = pd.DataFrame(df_dict_links)
    return df_nodes, df_links

## Application

In [18]:
gdf_paths = gpd.read_file(rf"{python_directory}/port_meadow_paths.geojson")
gdf_entry_points = gpd.read_file(rf"{python_directory}/port_meadow_points.geojson")

df_nodes, df_links = extract_nodes_links(gdf_paths, gdf_entry_points)

display(df_nodes)
display(df_links)
display(df_nodes.iloc[[109]])
print(xy_entry)

[(449100.80078, 209625.91316), (449865.56971, 207343.84408), (450222.45994, 207832.8085), (449392.62682, 209977.19482), (449393.11971, 209976.85282), (449396.46716, 209974.53034), (449398.17424, 209973.34595), (449854.85798, 207291.46669), (450080.3743, 206990.74571), (449569.81233, 209673.19653), (449536.65445, 209600.61965), (448599.54498, 205094.22852), (448577.63545, 205076.23226), (448537.07187, 205043.47475), (449490.91534, 205491.09577), (449503.48774, 205462.06087), (452149.37249, 204711.58942), (450476.04068, 207899.57311), (450475.22507, 207889.10561), (450474.75547, 207887.40314), (452700.17962, 207639.29113), (452607.90163, 207584.37043), (453035.49107, 206638.11465), (453035.41527, 206638.08025), (453031.73464, 206636.40888), (453030.40036, 206635.803), (453029.84207, 206635.5495), (453027.89311, 206634.66442), (453026.05684, 206633.83054), (453025.38565, 206633.52575), (453007.49458, 206630.36182), (452999.15583, 206629.91344), (452998.16975, 206629.86044), (452972.89521, 206628.50149), (451214.16384, 210140.59435), (451417.05968, 208649.99041), (452929.92978, 208416.57241), (452941.16465, 208412.19074), (452960.58636, 208405.20325), (453021.57527, 208753.33313), (453013.99191, 208746.7866), (448402.30774, 210216.65039), (448619.34636, 210139.59005), (448149.31607, 205803.01929), (447756.64631, 204574.19861), (447800.29103, 210511.89372), (452857.50756, 206022.50071), (452516.05437, 206195.42839), (452914.57686, 206277.33536), (452712.38077, 206296.41568), (452906.42705, 206298.55496), (452693.81114, 206304.68558), (452678.90163, 206426.55319), (452873.33817, 206623.1485), (452681.48195, 206656.83855), (452852.76865, 206676.4475), (452842.53908, 206828.16447), (453054.43522, 206877.10319), (452698.45228, 207006.79151), (452931.17199, 208430.79416), (452931.19199, 208430.79416), (452953.65173, 208507.88285), (452979.62098, 208398.35496), (452996.78156, 208798.96777), (453016.59694, 207232.09651), (453021.28671, 207188.98731), (453042.49972, 208383.8455), (451639.84803, 205228.80117), (451146.04767, 205272.66165), (452426.20352, 205276.43712), (452403.58398, 205290.57693), (452509.03207, 205306.48617), (452364.30498, 205377.59534), (452512.88261, 205513.30203), (452512.85262, 205513.48202), (452507.4828, 205540.4915), (452513.66274, 205561.09107), (452513.07276, 205562.45104), (452443.55431, 205646.42962), (452258.3781, 205747.32827), (452302.12736, 205772.41761), (450825.1357, 205852.43145), (451420.30437, 205858.50906), (451496.63293, 205862.81868), (451561.38181, 205896.01776), (451561.35181, 205896.01776), (451464.71365, 205897.75809), (451450.70393, 205901.91806), (451577.26168, 205948.43662), (452132.02124, 205981.38396), (451410.08498, 205983.63657), (451410.08498, 205983.65657), (451189.70926, 206008.23697), (451216.47877, 206016.28671), (451172.87964, 206034.79652), (451399.67534, 206042.28545), (451399.67534, 206042.30545), (451505.97334, 206050.40486), (452731.81677, 208903.38563), (451143.25728, 208958.42954), (452515.80103, 209016.06407), (452509.18121, 209038.72365), (452432.91308, 209217.99039), (450825.10445, 209230.73531), (452417.50349, 209268.48946), (450807.33505, 209317.16367), (451138.97991, 209876.3916), (451135.62028, 210012.34899), (451113.21075, 210023.14885), (451107.82086, 210025.16883), (451131.93046, 210056.00816), (451131.76046, 210056.06816), (451142.14029, 210070.75784), (451182.74955, 210096.9272), (451121.5308, 210121.01694), (451101.88139, 210210.43528), (450942.47452, 210228.25547), (450928.8049, 210281.38449), (450919.15521, 210345.15329), (450978.59407, 210349.55301), (451298.8679, 210352.85188), (450985.23411, 210429.42144), (450950.46485, 210462.98091), (450966.75455, 210467.44077), (451085.14236, 210504.46966), (451042.44332, 210570.95852), (450701.55982, 210578.1895), (450733.25924, 210589.67917), (450917.30579, 210616.53805), (451252.8107, 207145.38454), (450970.16623, 207219.6541), (452900.18923, 207270.8657), (451185.40239, 207282.78208), (452853.78029, 207313.41508), (452524.76717, 207440.75398), (452318.21129, 207464.41436), (451555.09623, 207520.42619), (450888.24868, 207524.0983), (450908.80833, 207532.95806), (450867.30914, 207545.37794), (452607.26604, 207584.66093), (452195.13421, 207616.45196), (452594.08644, 207623.97024), (452700.08442, 207639.07953), (452614.07612, 207645.24975), (451180.03484, 208147.34517), (450669.57519, 208374.39244), (452781.18473, 208379.80532), (452712.33609, 208410.73497), (452769.34534, 208562.30195), (452855.86392, 208651.90001), (452688.62714, 208705.50952), (451084.96783, 208725.1543), (450984.42007, 208816.85288), (450981.01017, 208828.97266), (451600.09772, 208832.71038), (452718.39688, 208841.83685), (450997.41988, 208841.99234), (451041.81902, 208854.37194), (451172.11649, 208886.31085), (451434.63473, 206066.75484), (452392.13655, 206095.50081), (452414.82619, 206134.16996), (452068.15283, 206143.14097), (450640.96998, 206150.02644), (451690.95006, 206153.63211), (452001.06415, 206161.24085), (451871.41761, 206607.9026), (451982.13547, 206610.75212), (451979.56552, 206614.12207), (451921.40681, 206684.81091), (452400.50755, 206726.99823), (451739.67048, 206747.2804), (451739.66048, 206747.3004), (451739.65048, 206747.3904), (451735.22063, 206778.78981), (451735.16063, 206779.03981), (451735.15063, 206779.08981), (451994.59566, 206816.81805), (452030.72499, 206834.70755), (451385.29734, 206836.92006), (451892.8777, 206840.51799), (450735.05975, 206926.34087), (451136.75233, 206969.48844), (451119.28272, 206989.61811), (451160.74197, 206999.27776), (451819.1696, 207012.30497), (451879.88848, 207036.38426), (451340.82879, 207062.92583), (451571.34451, 207077.77467), (452017.21595, 207088.84271), (450074.20526, 207845.63457), (450101.84081, 206374.9041), (450107.55046, 206271.37612), (450117.4403, 206287.11577), (450119.20026, 206282.64585), (450137.22969, 206186.91767), (450170.62337, 207843.26427), (450200.73859, 206239.44639), (450230.53359, 208400.03364), (450249.43019, 207273.08563), (450257.12751, 206235.83624), (450288.23364, 208842.61504), (450288.60365, 208850.50488), (450297.59343, 208830.33525), (450317.44309, 208839.44498), (450340.18268, 208840.14488), (450377.99942, 207875.67291), (450378.62181, 208784.40583), (450441.46824, 207895.54231), (450443.18803, 207830.39357), (450446.35805, 207857.983), (450448.90383, 206234.86552), (450450.98314, 205948.24109), (450463.69779, 207887.44238), (450467.23776, 207900.45212), (450475.04757, 207886.96235), (450475.11095, 209112.35891), (450485.77071, 209096.35919), (450548.82871, 208795.60489), (450568.96135, 206150.23672), (450575.55354, 207186.26621), (448415.9846, 209282.18526), (448688.17097, 209408.79118), (448735.94035, 209428.39051), (449058.69605, 209471.91767), (449643.9872, 209491.47426), (449108.50544, 209505.18669), (448974.69732, 209549.73661), (449491.6702, 209574.41305), (449552.55922, 209626.88175), (448873.34887, 209684.45453), (449536.24977, 209718.28993), (449156.4753, 209732.23179), (449684.82738, 209818.02758), (449656.7879, 209820.53763), (449705.96705, 209839.13712), (449665.88781, 209844.68715), (449440.33234, 209944.09606), (448771.64071, 209988.64949), (448757.3409, 209997.52942), (450025.74263, 210410.49522), (450027.2926, 210411.1952), (450083.84157, 210437.45448), (450114.731, 210451.6641), (450121.00089, 210454.89401), (450073.17199, 210522.7929), (450059.42232, 210548.31247), (450304.54751, 210551.27147), (450315.57749, 210648.96954), (450102.01182, 210707.32922), (450009.27367, 210730.39914), (447497.02187, 208857.27059), (447513.88174, 208787.36181), (447565.07049, 205693.64917), (447572.23049, 206176.83007), (447584.27027, 205679.1993), (447585.70036, 206176.81996), (447979.76636, 206078.05862), (448099.44516, 206252.50453), (448103.39512, 206237.18477), (448117.56496, 206154.69614), (448193.89422, 206273.6134), (448205.55411, 206304.84275), (448903.82247, 206147.59282), (448960.95068, 205680.3117), (448969.18119, 206079.7139), (448986.11101, 206152.38247), (449102.81847, 205910.93675), (449521.91183, 206315.5475), (449562.722, 206667.85037), (449578.12006, 206059.16236), (449650.94876, 206093.77139), (449656.12871, 206113.20099), (449700.23764, 206024.12258), (449703.2072, 205848.83592), (449718.07731, 206028.11243), (449740.52685, 206018.21253), (449769.22642, 206061.52157), (449825.72533, 206057.90142), (449972.62326, 206360.43488), (450028.8514, 206031.53115), (450032.61135, 206041.40094), (447476.3621, 208573.64616), (452515.14252, 205495.17238), (452515.14252, 205495.22238), (452519.14102, 204644.97864), (452533.61166, 205319.66581), (452557.6012, 205316.19578), (452570.84089, 205294.62616), (452587.10051, 205267.78662), (452598.65115, 205560.29076), (452798.61566, 204354.68293), (453018.66338, 205613.30822), (453068.41242, 205611.69812), (453078.9322, 205605.41821), (453079.13177, 205447.44129), (452065.72927, 204302.70664), (451519.72966, 204314.47838), (452264.40558, 204321.85555), (452391.33324, 204363.9943), (452401.47305, 204368.19418), (451501.40004, 204415.32661), (451805.29416, 204434.85526), (451716.27595, 204668.61137), (452148.55791, 204712.09891), (451381.64244, 204738.56109), (451394.4022, 204752.92079), (451407.21195, 204763.61056), (451438.47135, 204790.20998), (451418.52175, 204859.77877), (451245.6451, 204931.99792), (451545.85932, 204934.75706), (451339.98329, 204938.47755), (451563.86898, 204961.20654), (452483.77189, 205039.51153), (452483.75189, 205039.62153), (452411.90322, 205056.69152), (452465.95223, 205067.0411), (450967.61048, 205069.14609), (452479.42198, 205074.14091), (451540.13951, 205100.46405), (451915.27243, 205109.81267), (451102.67812, 205157.25404), (451497.28065, 205194.32225), (451554.03956, 205195.25208), (451917.65268, 205197.05086), (451207.74628, 205211.38269), (450951.69545, 203897.81375), (451833.18535, 204069.11008), (451845.09543, 204052.76005), (451874.18554, 204018.72997), (451894.00425, 204067.56985), (447461.08303, 204268.79469), (447482.21271, 204279.62441), (447540.22073, 205651.04017), (448385.49045, 205182.69366), (448385.52045, 205182.69366), (448404.12011, 205182.78359), (448429.67963, 205178.54358), (448430.59964, 205193.24328), (448465.62899, 205191.43318), (448465.93909, 205264.6217), (448520.52796, 205177.25326), (448596.19643, 205089.63472), (448669.69501, 205008.72593), (448722.8739, 204771.41993), (448947.30089, 205659.16216), (449228.36575, 205653.80134), (449231.73568, 205648.91143), (449511.77018, 205464.044), (449706.67575, 205171.28877), (449904.50181, 205177.87784), (449979.32014, 205105.55891), (450024.86887, 204343.43297), (450062.28811, 204285.65391), (450121.36694, 204257.43423), (450121.37694, 204257.42423), (450176.51584, 204180.75548), (450232.40516, 204123.51602)]

            id          xpos          ypos  sp_id  entry
0        n_id0  448974.69732  209549.73661     -1      1
1        n_id1  448982.32324  209544.78152     -1     -1
2        n_id2  448986.44756  209541.01583     -1     -1
3        n_id3  448999.89643  209529.89810     -1     -1
4        n_id4  449012.80734  209519.67696     -1     -1
...        ...           ...           ...    ...    ...
4505  n_id4505  448725.32657  209431.13858     -1     -1
4506  n_id4506  448727.11976  209431.76619     -1     -1
4507  n_id4507  448729.45089  209431.76619     -1     -1
4508  n_id4508  448730.52680  209431.67653     -1     -1
4509  n_id4509  448734.20283  209429.43506     -1     -1

[4510 rows x 5 columns]

            id     start       end  maxspeed
0        l_id0     n_id0     n_id1         0
1        l_id1     n_id1     n_id2         0
2        l_id2     n_id2     n_id3         0
3        l_id3     n_id3     n_id4         0
4        l_id4     n_id4     n_id5         0
...        ...       ...       ...       ...
4577  l_id4577  n_id4505  n_id4506         0
4578  l_id4578  n_id4506  n_id4507         0
4579  l_id4579  n_id4507  n_id4508         0
4580  l_id4580  n_id4508  n_id4509         0
4581  l_id4581  n_id4509   n_id301         0

[4582 rows x 4 columns]

          id          xpos          ypos  sp_id  entry
109  n_id109  449238.83798  209376.84998     -1     -1

[(449100.8007841008, 209625.91316479765), (449865.5697127742, 207343.84408132924), (450222.45993505896, 207832.8085025841), (449392.62681867473, 209977.19481771026), (449393.11971142964, 209976.8528208944), (449396.46716219984, 209974.53034251207), (449398.1742370755, 209973.34595353348), (449854.8579751864, 207291.46669264528), (450080.37429664936, 206990.74571389204), (449569.81232987053, 209673.1965252384), (449536.6544462647, 209600.61964821897), (448599.5449779812, 205094.2285169849), (448577.6354541221, 205076.23226383456), (448537.07186715305, 205043.4747456722), (449490.9153414556, 205491.09576503973), (449503.4877424249, 205462.06086719682), (452149.37249336625, 204711.58941630897), (450476.0406831457, 207899.57310590748), (450475.2250702208, 207889.10560618172), (450474.7554746713, 207887.40313995758), (452700.17961514374, 207639.2911262965), (452607.90163097053, 207584.37043189327), (453035.4910733717, 206638.11464697472), (453035.415274708, 206638.08024771954), (453031.7346395855, 206636.40888402332), (453030.4003631089, 206635.80299719132), (453029.8420729511, 206635.54950270493), (453027.8931073146, 206634.66442195355), (453026.0568396951, 206633.83054009802), (453025.38565153163, 206633.52574673464), (453007.49457511713, 206630.36182493926), (452999.15582760354, 206629.91344097973), (452998.16974563577, 206629.86044287903), (452972.89520786644, 206628.5014916166), (451214.1638407216, 210140.59435166477), (451417.0596750288, 208649.9904058164), (452929.9297822662, 208416.5724115909), (452941.1646543604, 208412.1907415567), (452960.5863616699, 208405.2032548082), (453021.5752735531, 208753.33312737342), (453013.9919052452, 208746.7866048342), (448402.3077434644, 210216.6503895205), (448619.3463571588, 210139.59004622186), (448149.31606998894, 205803.0192941081), (447756.6463126415, 204574.19861281908), (447800.2910264142, 210511.89372428902), (452857.5075594695, 206022.5007077821), (452516.0543650769, 206195.42839232017), (452914.5768594622, 206277.33535726357), (452712.38077089953, 206296.41568314843), (452906.42704738304, 206298.55495578918), (452693.811141067, 206304.6855824429), (452678.9016273475, 206426.5531867675), (452873.33817096305, 206623.14850103646), (452681.4819536214, 206656.83854941168), (452852.7686512115, 206676.4475003496), (452842.5390804751, 206828.16447056667), (453054.4352196762, 206877.10319307767), (452698.45228471153, 207006.79150807043), (452931.17199042527, 208430.7941560258), (452931.19199003687, 208430.79415611288), (452953.65172953135, 208507.88284657086), (452979.62097675493, 208398.35496302793), (452996.7815568847, 208798.9677653351), (453016.5969420729, 207232.09650797438), (453021.2867135524, 207188.98731022346), (453042.49972345267, 208383.84549902723), (451639.84802675195, 205228.80116739753), (451146.04766732384, 205272.66165140667), (452426.2035182604, 205276.43711723393), (452403.58398048073, 205290.5769266605), (452509.03207254666, 205306.48617361888), (452364.3049757413, 205377.5953357626), (452512.88261419046, 205513.30202543153), (452512.8526152839, 205513.48202195112), (452507.48279573175, 205540.491503014), (452513.6627410802, 205561.09106766892), (452513.0727561518, 205562.45104275935), (452443.5543103575, 205646.4296248447), (452258.37810464564, 205747.32827306644), (452302.12735746126, 205772.4176074881), (450825.13569567347, 205852.43144832144), (451420.3043674004, 205858.50905892614), (451496.632926733, 205862.81868125137), (451561.3818051885, 205896.0177565944), (451561.3518057608, 205896.01775670983), (451464.7136531232, 205897.7580946216), (451450.7039341001, 205901.91806458845), (451577.2616809574, 205948.43662275083), (452132.0212386874, 205981.3839587248), (451410.0849825364, 205983.63657319907), (451410.08498260356, 205983.65657279547), (451189.70925819245, 206008.23697255633), (451216.47876983136, 206016.28670562687), (451172.87963811087, 206034.79652281717), (451399.67534346523, 206042.2854533638), (451399.6753435087, 206042.3054529715), (451505.973341113, 206050.40486306342), (452731.81676875445, 208903.385625234), (451143.2572787113, 208958.42953993718), (452515.8010348596, 209016.0640685102), (452509.18121274747, 209038.723648609), (452432.9130751259, 209217.99039265036), (450825.104449539, 209230.73530902248), (452417.50348933355, 209268.48945734015), (450807.33505045355, 209317.16367031023), (451138.9799122993, 209876.3915969247), (451135.6202848448, 210012.34898695408), (451113.21074936766, 210023.14885408082), (451107.8208597309, 210025.1688332492), (451131.9304554985, 210056.0081575503), (451131.76045896683, 210056.0681569653), (451142.14028862026, 210070.7578388984), (451182.7495532538, 210096.92719829682), (451121.5308048271, 210121.01693887508), (451101.8813868891, 210210.43528004526), (450942.474522011, 210228.25546739704), (450928.8048952528, 210281.38448676968), (450919.15521082823, 210345.1532870406), (450978.5940733225, 210349.5530051262), (451298.86790341465, 210352.85188147397), (450985.2341122975, 210429.4214411556), (450950.4648488218, 210462.98090778652), (450966.7545458898, 210467.4407679949), (451085.1423590809, 210504.46966383926), (451042.4433187772, 210570.95852107805), (450701.55982395104, 210578.18949882506), (450733.2592414457, 210589.67917254905), (450917.30579430924, 210616.5380506509), (451252.8106992378, 207145.3845415403), (450970.1662250062, 207219.6541025006), (452900.1892325751, 207270.86570022942), (451185.40238965244, 207282.7820833932), (452853.7802896402, 207313.4150815332), (452524.76716996176, 207440.75398432644), (452318.2112926284, 207464.41435884545), (451555.0962284759, 207520.42619352165), (450888.2486840596, 207524.09830077481), (450908.8083273168, 207532.95805643575), (450867.3091393322, 207545.37794255378), (452607.26604438154, 207584.66092890617), (452195.1342054302, 207616.4519597987), (452594.0864355286, 207623.970236281), (452700.0844162806, 207639.07953068241), (452614.07611735584, 207645.24975398445), (451180.0348362225, 208147.34516510327), (450669.5751922623, 208374.39243780146), (452781.18472808326, 208379.8053179538), (452712.3360929034, 208410.73497106833), (452769.3453395744, 208562.30194884405), (452855.86392181425, 208651.90000811446), (452688.6271394711, 208705.50951857388), (451084.96783448383, 208725.15430472296), (450984.4200686057, 208816.85288396507), (450981.01017196267, 208828.97265799972), (451600.0977167123, 208832.71038118954), (452718.39687705936, 208841.8368540777), (450997.4198787958, 208841.99234373943), (451041.8190203446, 208854.3719425004), (451172.1164895082, 208886.3108524073), (451434.6347326068, 206066.7548354654), (452392.1365532845, 206095.50080560794), (452414.8261911051, 206134.1699601842), (452068.1528334566, 206143.14096935285), (450640.9699789206, 206150.02643713437), (451690.9500585247, 206153.63210914162), (452001.0641542246, 206161.24084569525), (451871.41761399264, 206607.90260106663), (451982.1354677997, 206610.75212463964), (451979.56552487577, 206614.12206852477), (451921.4068076793, 206684.81091096834), (452400.5075487039, 206726.9982268921), (451739.67047700303, 206747.28040399094), (451739.6604772367, 206747.30040364043), (451739.6504776286, 206747.3904019388), (451735.22063196305, 206778.78981065855), (451735.16063365655, 206779.03980604938), (451735.1506339578, 206779.08980511752), (451994.595658152, 206816.81804587675), (452030.7249877971, 206834.70755226247), (451385.2973443881, 206836.92005880852), (451892.8777012717, 206840.51798710768), (450735.05975435965, 206926.34087012417), (451136.75233030313, 206969.48844426917), (451119.28272075945, 206989.61811398), (451160.7419720395, 206999.27776341967), (451819.16959601635, 207012.3049679803), (451879.88848013, 207036.38426270545), (451340.828790145, 207062.9258273751), (451571.3445121212, 207077.7746702297), (452017.2159520554, 207088.84270747472), (450074.2052599396, 207845.6345673495), (450101.84080839506, 206374.90410345874), (450107.55045709613, 206271.37611909903), (450117.4403037169, 206287.11577127082), (450119.20025950926, 206282.64585245698), (450137.22969175136, 206186.91766646766), (450170.62337495724, 207843.26427326375), (450200.7385948257, 206239.44638802204), (450230.53358870547, 208400.03364122042), (450249.43019161536, 207273.08562778257), (450257.1275050498, 206235.83624150924), (450288.23363848927, 208842.61504309863), (450288.6036533936, 208850.50488331896), (450297.5934324021, 208830.33525020885), (450317.44309214375, 208839.44498470775), (450340.1826755417, 208840.1448757529), (450377.99942457885, 207875.67290697084), (450378.6218136657, 208784.4058276246), (450441.4682438134, 207895.54230595496), (450443.1880279396, 207830.39356798586), (450446.3580468221, 207857.98299570446), (450448.9038251034, 206234.86552122125), (450450.98313646566, 205948.24109235842), (450463.6977897357, 207887.44237882947), (450467.2377565572, 207900.45212094922), (450475.04756778205, 207886.9623472229), (450475.11095081666, 209112.35890977381), (450485.7707105818, 209096.35918580816), (450548.82871059584, 208795.60488504887), (450568.96135253954, 206150.23671627138), (450575.55354457913, 207186.26620501617), (448415.98460456135, 209282.18526374723), (448688.1709742762, 209408.79118146206), (448735.9403482714, 209428.39050555893), (449058.6960510834, 209471.9176731328), (449643.9872000523, 209491.47425662045), (449108.5054449552, 209505.18668860284), (448974.6973153275, 209549.73660843726), (449491.67019986885, 209574.4130464805), (449552.5592241672, 209626.88174742), (448873.34886616055, 209684.45453263092), (449536.2497735187, 209718.28993023862), (449156.4752979459, 209732.23179193307), (449684.82737689477, 209818.02758162748), (449656.7879022005, 209820.53762784816), (449705.96705365693, 209839.1371161886), (449665.8878122137, 209844.6871461519), (449440.33234258834, 209944.09605866863), (448771.64071362413, 209988.64949257462), (448757.3409023718, 209997.52941851487), (450025.742629773, 210410.4952150071), (450027.2926014414, 210411.1951959203), (450083.84156710183, 210437.45448477747), (450114.73099967296, 210451.66409799358), (450121.0008851524, 210454.89401282824), (450073.17198817915, 210522.79290279275), (450059.4223224182, 210548.31247056276), (450304.54750627757, 210551.2714718795), (450315.5774924473, 210648.9695449671), (450102.01181624515, 210707.32922372263), (450009.27367449127, 210730.39913544524), (447497.0218714038, 208857.27059498488), (447513.881735782, 208787.36180543067), (447565.07048644, 205693.64916826837), (447572.2304922983, 206176.83006931964), (447584.2702714172, 205679.19930127135), (447585.7003558853, 206176.81996263465), (447979.76636341953, 206078.05861685646), (448099.44516249176, 206252.50452773413), (448103.3951204659, 206237.18477207847), (448117.5649638733, 206154.69614355994), (448193.8942192939, 206273.6134016171), (448205.5541110536, 206304.84274839674), (448903.8224697279, 206147.59282201756), (448960.95067725563, 205680.31170209026), (448969.18118713284, 206079.71390277933), (448986.1110107764, 206152.38246985374), (449102.8184722949, 205910.9367543409), (449521.91183060827, 206315.5475028836), (449562.72199646785, 206667.85037306562), (449578.1200567494, 206059.16235965135), (449650.94875946315, 206093.77139114717), (449656.12871197524, 206113.2009868176), (449700.23763596604, 206024.12257563393), (449703.2072049547, 205848.83591555047), (449718.0773065814, 206028.11242708244), (449740.52685329557, 206018.2125349436), (449769.2264181477, 206061.52156748658), (449825.72533153277, 206057.9014186507), (449972.62326478417, 206360.43488376273), (450028.8513958734, 206031.5311463112), (450032.61134784867, 206041.4009372575), (447476.36209857365, 208573.6461583572), (452515.1425182816, 205495.17237883003), (452515.1425184296, 205495.22237783158), (452519.14101642725, 204644.97864219657), (452533.61165548995, 205319.66580956668), (452557.601200069, 205316.19578051305), (452570.84089123073, 205294.62615590484), (452587.1005114437, 205267.78662303992), (452598.6511475352, 205560.29075804783), (452798.61565656104, 204354.682933665), (453018.66338268464, 205613.30822215305), (453068.41242338583, 205611.6981200223), (453078.93220438994, 205605.41821420303), (453079.1317711563, 205447.44129297388), (452065.72926792613, 204302.70664110885), (451519.7296625629, 204314.47837686463), (452264.4055781542, 204321.85554791905), (452391.333237613, 204363.99429958704), (452401.4730512059, 204368.19418425916), (451501.40004444204, 204415.32660809986), (451805.2941627991, 204434.8552596192), (451716.275947814, 204668.61137354956), (452148.55790866166, 204712.09891038242), (451381.6424404498, 204738.56108879286), (451394.40219680034, 204752.9207896549), (451407.2119514866, 204763.61055774876), (451438.47135330667, 204790.20998376556), (451418.52175423957, 204859.77877175342), (451245.64510350826, 204931.99791771622), (451545.8593158007, 204934.75706409186), (451339.9832858397, 204938.47754649218), (451563.868975562, 204961.2065379428), (452483.77188545186, 205039.51152703527), (452483.7518858797, 205039.6215250978), (452411.90321691084, 205056.69152165652), (452465.9522281251, 205067.04109770822), (450967.6104766427, 205069.14609274134), (452479.42198419844, 205074.1409087823), (451540.1395079118, 205100.46405228245), (451915.2724277337, 205109.81267149956), (451102.67812184134, 205157.2540382262), (451497.2806515375, 205194.3222549731), (451554.0395627031, 205195.25208482234), (451917.6526782757, 205197.05086098134), (451207.7462785756, 205211.38269113068), (450951.6954533571, 203897.81374975137), (451833.1853463122, 204069.11007996136), (451845.0954340971, 204052.76005075738), (451874.1855350508, 204018.72997496766), (451894.0042452245, 204067.56985333515), (447461.0830277515, 204268.7946908914), (447482.21271034837, 204279.6244072009), (447540.22072732734, 205651.04016871646), (448385.49045190355, 205182.69366208615), (448385.520451351, 205182.69366196857), (448404.1201092759, 205182.78358913254), (448429.6796327182, 205178.5435772987), (448430.59963763197, 205193.24327649054), (448465.62899054174, 205191.43317969533), (448465.93909428833, 205264.6217013076), (448520.52795919933, 205177.2532559468), (448596.19643262925, 205089.6347221585), (448669.6950053715, 205008.7259342795), (448722.87389874563, 204771.4199348524), (448947.30089204776, 205659.1621616786), (449228.36574983795, 205653.80134370364), (449231.7356799416, 205648.91142704582), (449511.7701831502, 205464.043996113), (449706.67575258715, 205171.28877340705), (449904.5018072736, 205177.877842339), (449979.3201384752, 205105.5589077617), (450024.8688671016, 204343.4329666379), (450062.28811077756, 204285.6539135874), (450121.36694293015, 204257.43423430616), (450121.37694273173, 204257.42423445982), (450176.515840004, 204180.75548120402), (450232.40516083245, 204123.51601718512)]

---
# Extract nodes: Polygons

In [20]:
greens = gpd.read_file(rf"{python_directory}/port_meadow_single_27700.geojson")
df_nodes_paths = df_nodes

In [21]:
green = greens["geometry"][0]
print(greens["geometry"][0])
print(green.exterior.xy)

# Extract x and y coordinates of the nodes in the outer polygon line
x,y = green.exterior.xy
xy = list(zip(x,y))
print(xy)

# Initialise the needed parameters
xy_list = []
x_list = []
y_list = []
n_id_list = []

n_id_counter = len(df_nodes_paths)
for i in range(len(x)):
    #-----------------
    # Nodes
    #-----------------
    # Check if the node has already been given an id
    if (x[i], y[i]) not in xy_list:
        xy_list.append((x[i], y[i]))
        x_list.append(x[i])
        y_list.append(y[i])
        n_id_list.append(f"n_id{n_id_counter}")
        n_id_counter += 1

df_dict_nodes_green = {
        "id": n_id_list,
        "xpos": x_list,
        "ypos": y_list
    }
df_nodes_green = pd.DataFrame(df_dict_nodes_green)
display(df_nodes_green.head())

POLYGON ((449316.4451014007 209813.73964280786, 449317.36098156613 209811.28948241024, 449317.9538749761 209811.57037336618, 449318.36617037567 209811.76036717673, 449320.46034706425 209812.74003546685, 449332.79473134025 209795.33527909662, 449345.09621925757 209779.2400985337, 449363.1938039863 209755.23732724087, 449367.4894278983 209749.28910989297, 449370.894565957 209744.14058345003, 449381.3408825296 209730.39477104013, 449392.1911901154 209715.839070984, 449410.8411660185 209690.2867497161, 449421.29569218494 209675.94118381478, 449424.445239626 209671.59245500353, 449424.78333423444 209671.22256061295, 449426.1437127401 209669.81298152677, 449430.101346758 209664.41466968268, 449430.2909389705 209662.39521092112, 449438.8738580293 209649.4591488812, 449439.3438482389 209648.98935720074, 449439.93743572605 209648.33956889313, 449440.72341909714 209647.4552848728, 449440.7413187355 209647.44168509933, 449440.85841616447 209647.27388823463, 449449.79012153926 209635.043615469, 449455.3389003496 209627.34595860878, 449459.9889978523 209620.53798597434, 449468.7945041039 209607.79192391637, 449486.6612112065 209582.0697030215, 449488.40907246806 209579.44055219763, 449489.29125283065 209578.0809776939, 449491.9637933563 209573.9693547772, 449519.96827185585 209531.6449451577, 449524.5381708052 209524.89717057016, 449541.7204902828 209499.34494527726, 449543.6910463224 209496.29590213258, 449548.390542317 209489.34803091898, 449553.18913567957 209482.09016575484, 449558.54001700116 209474.09261402814, 449562.73672371294 209467.74453182466, 449566.8426328573 209461.69644362916, 449571.5422290462 209454.84846997797, 449575.73883622326 209448.69038364128, 449579.3418566219 209443.441980374, 449583.88475564343 209436.5941070821, 449588.79044723214 209429.44623869256, 449597.38985554967 209416.30028203235, 449600.44048729126 209411.54157027736, 449604.9339871597 209404.69379684346, 449608.6359038557 209398.7456074381, 449612.63471458654 209392.5975210893, 449616.8395210137 209386.24933810887, 449621.39071912726 209379.15156941366, 449625.9336176145 209372.14369881194, 449630.9878042663 209364.1960458238, 449635.687399098 209356.8983805293, 449638.35703926056 209352.71835773112, 449638.4330375576 209352.59975991887, 449638.47423664597 209352.53956102155, 449638.476536595 209352.53616108297, 449641.0382792388 209348.55083460925, 449640.84038155136 209348.05094570346, 449640.4363837054 209346.05158868036, 449640.2384844453 209344.95191223506, 449640.09008425236 209343.8422358139, 449640.0900801891 209342.29276799405, 449638.7378965618 209339.09373932506, 449638.33390028996 209337.69416985346, 449637.0889112939 209333.19556780078, 449635.7862228324 209328.49697012553, 449634.08773769124 209322.29890505451, 449632.8839489953 209318.200194587, 449631.63895922154 209313.40159882657, 449630.5341664631 209308.4432058843, 449629.4869730702 209303.64460942498, 449628.4893804729 209299.49589928892, 449627.8379837619 209296.19697023235, 449626.8898873793 209290.9485827844, 449625.7354933369 209285.15030753386, 449624.8862982887 209281.10159481608, 449624.2349028911 209278.30245539575, 449623.33621084713 209275.05342624744, 449621.7367266442 209269.8950393877, 449620.3845382006 209264.84654934547, 449619.18904754176 209260.0480535421, 449617.7378592154 209254.34977740707, 449616.8886657479 209250.90085228044, 449615.78387448005 209246.502247857, 449614.736681896 209242.00364531425, 449613.9369852734 209237.69493790873, 449613.7885861622 209236.99515301612, 449613.0382886613 209232.69644522615, 449611.93339399947 209226.99826787633, 449611.6860947386 209225.54869895498, 449610.93579815666 209221.5998839087, 449610.086502999 209217.50117235357, 449608.1902118637 209207.60418537876, 449607.2337176037 209203.09558278648, 449605.0900329769 209193.9483812055, 449604.2408388728 209190.24956138787, 449603.53994440264 209187.45042228897, 449602.48465434136 209183.8515011879, 449600.7861707179 209178.20322518656, 449597.83449894673 209168.29634262534, 449596.03701701877 209162.59806810465, 449594.6354300519 209157.74957440142, 449593.4893407533 209153.80076100206, 449592.48344862193 209149.75204915588, 449591.0900586357 209143.80387835955, 449589.8368660796 209137.8557070449, 449588.58357467817 209132.34742658614, 449587.5364810897 209127.4489326444, 449586.1347911358 209121.45076299168, 449585.23609691724 209117.3520518451, 449584.3869042733 209114.2030207304, 449583.1336166968 209110.15420992975, 449581.53413430124 209105.65560985886, 449571.9369171195 209069.90659233497, 449570.53532902163 209064.608308286, 449569.33974011894 209060.44949968968, 449568.58944659017 209057.6503610036, 449569.08413319645 209056.0008934487, 449569.48812159937 209054.40142520907, 449569.78501418856 209053.65163967223, 449571.3349802358 209051.55227733823, 449573.58583157905 209048.7531268213, 449574.2372176559 209048.00333988178, 449574.938002824 209047.253552749, 449575.68828734395 209046.60376333253, 449577.98864182306 209045.35418030008, 449580.7836876065 209044.25449218543, 449585.59039486566 209042.55500861665, 449598.1391519205 209037.80635792192, 449604.9330205682 209035.30708306702, 449608.7338473389 209034.00749506697, 449613.83744860196 209032.10811437282, 449618.18256431946 209030.40853250946, 449619.6336362193 209029.85873819102, 449621.08470796153 209029.2489451195, 449622.3379829701 209028.49915574078, 449623.4839598185 209027.6993678264, 449625.03401285765 209020.65150819597, 449624.7867129447 209018.9520445072, 449623.6324265509 209016.05300936673, 449622.23894298216 209012.55408766295, 449620.8868581286 209008.85516996, 449620.2849652575 209007.35560354247, 449619.7902702863 209005.8061377349, 449619.4851722243 209004.406568058, 449619.3367712821 209003.00699775305, 449619.3862635579 209000.4077516098, 449619.32026201935 208999.35807369807, 449620.3838301543 208994.65956715407, 449621.488599076 208990.55084816308, 449622.2883725797 208986.05213849782, 449622.48625845613 208982.05342084623, 449622.58514982153 208979.45417449268, 449622.58514300553 208976.8550285331, 449622.2883405966 208973.85589208908, 449621.9832328349 208968.75749932334, 449621.28242052544 208959.1504019181, 449620.98560946685 208952.8523340816, 449620.98559164023 208946.05447543855, 449620.48258358665 208939.45651468477, 449619.888980347 208934.058129357, 449619.68288020516 208932.55866137845, 449617.9843857274 208922.75167225947, 449617.3824844782 208918.05307244026, 449616.98667917686 208913.25457386137, 449616.8877660547 208907.55629278906, 449617.1845453921 208901.75811217033, 449617.786415445 208894.56025940477, 449618.48718836834 208889.15196900337, 449620.98538130353 208865.8590430998, 449621.6861484749 208858.26139818644, 449622.2880239952 208853.1530019116, 449623.1866951257 208848.4543958743, 449624.58834833896 208840.45685631904, 449625.9817009124 208832.1594230152, 449627.48225229455 208824.16188299825, 449628.4881208897 208819.2533808184, 449629.98867882486 208813.75508881267, 449630.9863428676 208807.057123837, 449631.7860087163 208799.65937423002, 449632.58577744797 208793.36130175297, 449633.3855440761 208786.26344588946, 449633.98741405894 208779.05569313414, 449635.1828642303 208764.95995284565, 449635.48794782534 208758.9617610054, 449635.58683557936 208753.16356639628, 449635.1828352846 208748.85484674288, 449634.9849344437 208746.35569318786, 449634.8860315969 208743.75644104037, 449634.8860294414 208742.5567629349, 449635.08382363623 208741.35718398285, 449635.3889160304 208740.25750275824, 449635.98260327737 208739.2578184803, 449634.5891271976 208738.25814263173, 449633.78944034065 208737.3583624452, 449632.78355747194 208736.55868130148, 449631.1847855485 208735.7594026639, 449630.18640272313 208735.0591196739, 449629.1887188131 208733.75954761065, 449627.787142006 208732.25998090848, 449626.4679640929 208730.99040965945, 449623.4832145134 208728.36117025622, 449619.7895777436 208725.56203694496, 449615.2878553933 208722.46301250352, 449611.4869210104 208719.86377596785, 449607.68598612054 208716.96474488388, 449603.7861523611 208713.6557216706, 449601.7825860544 208711.75636474643, 449594.2880125242 208704.85842205846, 449591.78975436004 208702.35927812022, 449588.08781690744 208698.96025563288, 449584.1879829725 208695.46133578132, 449580.4860462721 208692.4623059734, 449574.9866409701 208688.36360372993, 449572.29058708606 208686.16425509902, 449567.58266737603 208682.16544766293, 449562.99024538015 208678.0567417135, 449559.5851038401 208675.35760511103, 449555.6852718286 208672.85836693534, 449551.18354997365 208669.75934217667, 449547.5888116768 208666.8602099645, 449543.6888780467 208663.3612899168, 449540.58882978314 208659.96236468322, 449536.3839005235 208655.66366040794, 449533.58884749643 208652.7645247808, 449529.9859089769 208649.56559796788, 449526.68786532676 208646.66646441817, 449523.29102184717 208642.757649604, 449520.4876682267 208639.35872303287, 449519.39108659123 208638.15904939454, 449518.286304945 208636.85947760323, 449517.38761947444 208635.55990494805, 449516.88472665445 208634.26023064286, 449516.48893184843 208632.96065589262, 449516.29103419627 208632.16087123594, 449516.18383502524 208631.46108439268, 449516.29103170667 208630.66139846743, 449516.58782486455 208629.86161175178, 449517.18971252005 208629.16182195308, 449517.7834006592 208628.6619285561, 449523.6866811362 208622.76371110545, 449526.78681816574 208619.5647563202, 449530.8845352838 208615.56591193943, 449536.88681423006 208609.9575889262, 449551.78531363735 208596.1617779637, 449555.99022853444 208592.16293328337, 449561.98420733155 208586.56461033243, 449567.8875877394 208580.9662878071, 449571.688509503 208576.66755034967, 449574.9864417982 208573.05870242935, 449578.48227160505 208570.15954079543, 449581.8874036 208567.56027409108, 449588.6894668111 208561.86204985692, 449593.685866779 208557.96320032346, 449601.8895022677 208551.46508500964, 449604.989639991 208548.96591782675, 449610.7858239919 208544.5671742222, 449618.08247810893 208539.1588429202, 449622.48528961977 208535.65988869488, 449628.2814725498 208530.76135432482, 449632.08229648654 208527.96218985075, 449637.98567838554 208523.66344416438, 449642.28129264456 208520.66438135842, 449644.8866404826 208518.76490539947, 449648.18457354116 208515.86574486876, 449651.5815049069 208513.06658212305, 449655.0856346084 208510.46741530427, 449656.68510194414 208508.96783617506, 449658.6886600697 208506.56857183098, 449664.1879461349 208500.56035919458, 449669.4811361874 208494.662145435, 449675.68130788155 208488.0641408309, 449678.08055775386 208485.26498225704, 449680.68600282085 208481.96593199612, 449687.9827480245 208472.26887972798, 449689.28542022663 208470.45940754417, 449693.0863390529 208465.16098906874, 449697.1839513304 208459.36277856812, 449699.9872915984 208455.56393674656, 449703.58201585384 208451.1653027258, 449706.8799454625 208446.6665717517, 449710.58196537377 208441.0682592991, 449714.8857733395 208435.1600501305, 449718.28269889025 208429.5617389651, 449722.7844030419 208423.66352889233, 449725.57934362267 208420.06468358962, 449727.8796931109 208416.26574394008, 449729.6853524649 208412.76680079085, 449730.48503398325 208410.9674305452, 449731.38381382305 208409.2678580777, 449733.88196124794 208406.36880119512, 449737.27889153187 208403.36964257137, 449740.58502446016 208400.87047516188, 449745.28462878655 208397.1615243823, 449749.08555195725 208394.46235870087, 449751.6826989559 208392.3629868336, 449753.6862571331 208390.2636173356, 449756.08550629485 208387.3644609342, 449758.38575634 208383.9655140951, 449760.28211379435 208380.4665707072, 449761.98057458136 208376.7677317771, 449763.78623313515 208372.96879426733, 449765.4845966125 208370.66952969437, 449769.8791978643 208362.56196096825, 449771.37976387265 208359.66280820058, 449773.7790091844 208354.86428673036, 449775.98035957897 208350.7655532193, 449777.1841329165 208348.76618514495, 449779.7812728596 208343.16787760548, 449781.578631229 208339.26904205314, 449783.2852911023 208335.27020870592, 449783.9778734866 208332.970948171, 449787.3829929143 208324.76338539767, 449788.2816709835 208322.26422773307, 449789.48543854576 208317.36571291235, 449790.48310861934 208311.76741175103, 449791.67857670685 208307.06879331078, 449793.1791362362 208300.97059937275, 449795.1825846079 208294.0627183469, 449796.18025639927 208289.36420070776, 449796.88103302266 208284.26569157303, 449797.6808036063 208277.06792059948, 449798.48057714506 208271.3696221013, 449799.68424082303 208264.5717422308, 449801.48168782494 208255.06460981222, 449802.9822454146 208248.06673249393, 449803.68302177003 208242.86832523457, 449803.97981076536 208240.16917365108, 449804.4827958356 208237.46992127504, 449805.6782657353 208233.77108457888, 449807.3849221154 208228.172780807, 449810.58394564607 208220.3651118733, 449817.17989080463 208205.7695546213, 449819.1833437985 208201.37092774414, 449820.88180199 208196.67230756138, 449821.9783756578 208193.97315295663, 449823.08314936305 208191.37389648508, 449825.6802915459 208187.26516205358, 449828.2774327178 208182.666536636, 449831.17966581974 208176.9682302848, 449834.98057565576 208168.27087566967, 449837.1819232777 208163.17246101738, 449839.4822677669 208157.4741570346, 449842.0794057181 208151.36605948018, 449845.1794344366 208145.46785617847, 449850.7777095863 208136.77049492887, 449852.0803793463 208134.17123781086, 449853.0780522871 208130.2724057606, 449853.67993525066 208127.57325314055, 449854.3807161114 208124.77410198917, 449856.1780720526 208120.0654818298, 449858.8824104032 208115.26695991843, 449867.2839205632 208101.27118585142, 449869.8810629114 208097.47234601807, 449873.5829809357 208092.17392965476, 449876.5759158354 208088.4750865281, 449879.4780509854 208084.06635683187, 449881.9762957507 208080.56741191034, 449885.77721380483 208076.26877685852, 449888.97624484584 208072.66983118874, 449891.27649376355 208069.37078336853, 449893.67573825794 208064.87215729582, 449895.6792909653 208060.67342718574, 449897.57564655115 208056.8745901187, 449900.57678002515 208052.67585632036, 449903.2810181165 208047.96733303525, 449906.0760544509 208043.26870925486, 449909.1761859315 208039.069975145, 449913.8756819359 208032.67197567248, 449918.8803715669 208026.07387880358, 449923.7778640369 208019.87577500567, 449928.3784634168 208014.2674614648, 449940.9766885692 207999.37198988692, 449943.0790422049 207996.67283197277, 449951.5795578667 207987.27557422605, 449954.67959065654 207983.87662561255, 449956.18025713327 207981.7772588773, 449958.48050618585 207978.76820602157, 449963.3779994093 207973.16989149363, 449970.67474182195 207965.57220518118, 449974.6734546791 207961.0734737093, 449976.67701155617 207959.07410335005, 449978.37547541846 207957.5745248666, 449984.2787478318 207951.4764160753, 449986.3812014356 207948.87715647556, 449987.5766747817 207947.2776816964, 449989.9760204003 207943.66873970215, 449993.9747280018 207936.8708508918, 449998.77321915596 207929.67296661576, 450005.8226575118 207918.37645008368, 450007.9251092009 207914.97740537836, 450012.08051513287 207908.91930248158, 450019.47615344246 207900.7717266134, 450021.9742954562 207896.52299627825, 450022.7740772454 207895.3234156099, 450022.82357606053 207895.2234172832, 450022.92247391597 207895.12341877876, 450022.9801725729 207895.02352042048, 450023.0791704262 207894.9235219154, 450023.12856924336 207894.82352358935, 450023.2275670975 207894.72352508357, 450023.5243607743 207894.4736286422, 450024.7281356043 207893.67383911845, 450029.27934170875 207891.224568094, 450033.32755812193 207889.0252942617, 450040.12961919553 207886.0261253676, 450041.9269809968 207884.57654576673, 450051.02928868897 207877.77863907313, 450052.9256470356 207875.66927137494, 450053.9727238399 207874.41959079064, 450054.9291024062 207873.17001052882, 450056.47916749184 207871.07064389763, 450056.6770628481 207870.72074967623, 450057.17175163573 207870.02096088015, 450057.42734598333 207869.72106552368, 450057.6747403756 207869.37117112597, 450058.07873092656 207868.6713826534, 450060.329574972 207863.32297377998, 450062.17642037064 207855.12551920046, 450062.8771991967 207852.15637430432, 450063.503781463 207850.21701171517, 450063.70167510054 207849.33722899447, 450063.9077698326 207848.897437251, 450064.02326698456 207848.68744113075, 450064.1881628607 207848.36754708277, 450064.31175988296 207848.16765073204, 450064.37775842694 207848.10765172268, 450064.4272573485 207848.0676523621, 450064.4766563005 207848.0376528019, 450064.5261552221 207847.99765344203, 450064.5838540135 207847.96765385062, 450064.6333529918 207847.94765408715, 450064.69925162254 207847.91765446245, 450064.75705043913 207847.89765466645, 450064.8724481347 207847.8776546665, 450065.0126453474 207847.85775457474, 450069.3494552244 207845.8782796199, 450071.7074056999 207844.61869698542, 450075.10433339636 207842.4693288398, 450076.4235032774 207840.91985581792, 450076.5718998166 207840.7199593765, 450076.7285963363 207840.56996188255, 450076.8769928753 207840.37006544258, 450077.2727831685 207839.67027833586, 450077.6272742653 207838.97049137717, 450078.42705355 207837.171025306, 450079.27623187186 207835.37155906128, 450079.62252312887 207834.67177213158, 450080.0265132613 207833.97198499588, 450080.1749095138 207833.67209059384, 450080.3728048025 207833.37219601974, 450080.52120105585 207833.07230162126, 450080.72739618254 207832.7724070181, 450081.32098247844 207832.02262023016, 450081.7249728958 207831.42283104942, 450085.12189743936 207828.17378536385, 450085.7731840368 207827.92388815287, 450086.47406966705 207827.6738907703, 450087.12535640696 207827.47399253823, 450089.1289159437 207826.9739956312, 450089.326812088 207826.97399492812, 450089.57410712726 207826.9240950708, 450089.772003129 207826.8741953834, 450090.77788353036 207826.87419180776, 450091.3220730706 207826.9240888534, 450091.8744625942 207827.02408484352, 450097.9756474355 207828.32363659982, 450099.57521741407 207828.72352274152, 450100.42440144107 207828.9235156366, 450102.82365569647 207829.27339995728, 450103.5245423272 207829.37329542456, 450105.0251136635 207829.5732860043, 450105.77539918834 207829.62328231597, 450106.6740818232 207829.6732780973, 450107.62216349423 207829.72317371058, 450109.82362031844 207829.62326792552, 450112.57736638066 207829.52316017862, 450114.52322847047 207829.52315325954, 450115.2735137096 207829.47325161443, 450117.6232679299 207829.47324326012, 450120.3276161001 207829.77312752, 450123.92234763934 207830.32300350873, 450127.121386888 207830.87278090755, 450130.2215279216 207831.37265967758, 450134.9210390849 207832.32232357503, 450139.0270615264 207833.1719916275, 450140.57713218755 207833.471979993, 450142.077703813 207833.7718685352, 450142.37449831713 207833.8717654398, 450142.7207917143 207833.921763186, 450143.02578591544 207833.9717610823, 450144.82325132797 207834.12175163097, 450148.1706868312 207834.3716346299, 450152.1777099147 207834.77151222684, 450156.7700215963 207835.1713877407, 450163.6710891625 207835.87114892987, 450169.47547780885 207836.4709160591, 450175.4695630474 207837.17068047624, 450176.82163713843 207837.32067261025, 450179.1714926535 207837.77045507682, 450186.22085935087 207839.17000146164, 450191.3244628053 207840.16966292117, 450193.1713278345 207840.51954921876, 450195.0758915963 207840.81953633024, 450197.475145865 207841.16942066583, 450198.72012218816 207841.36931216292, 450200.62468595034 207841.6691992777, 450204.37611448485 207842.22907452576, 450208.0698439701 207842.72875120857, 450212.324262967 207843.37862283265, 450212.9096517658 207843.44861932838, 450215.4738026235 207843.7285045095, 450216.3229865142 207843.87849843205, 450217.17227011465 207843.92849439534, 450218.0709528964 207844.02838916733, 450218.6233421365 207844.02838720463, 450218.7717393903 207844.0783856553, 450218.9696355353 207844.0783849529, 450219.1757313767 207844.02838524332, 450219.5715236669 207844.02838383854, 450219.67042159627 207843.97848450

         id           xpos           ypos
0  n_id4510  449316.445101  209813.739643
1  n_id4511  449317.360982  209811.289482
2  n_id4512  449317.953875  209811.570373
3  n_id4513  449318.366170  209811.760367
4  n_id4514  449320.460347  209812.740035

In [22]:
df_nodes_collated = pd.concat([df_nodes, df_nodes_green], ignore_index=True)
display(df_nodes_collated)

            id           xpos           ypos  sp_id  entry
0        n_id0  448974.697320  209549.736610   -1.0    1.0
1        n_id1  448982.323240  209544.781520   -1.0   -1.0
2        n_id2  448986.447560  209541.015830   -1.0   -1.0
3        n_id3  448999.896430  209529.898100   -1.0   -1.0
4        n_id4  449012.807340  209519.676960   -1.0   -1.0
...        ...            ...            ...    ...    ...
6004  n_id6004  449285.196654  209800.143997    NaN    NaN
6005  n_id6005  449295.140044  209805.292337    NaN    NaN
6006  n_id6006  449297.992813  209806.741892    NaN    NaN
6007  n_id6007  449298.561706  209807.041783    NaN    NaN
6008  n_id6008  449315.340222  209815.749013    NaN    NaN

[6009 rows x 5 columns]

In [23]:
df_collated = df_nodes_collated
x_max = max(df_collated["xpos"])
x_min = min(df_collated["xpos"])
y_max = max(df_collated["ypos"])
y_min = min(df_collated["ypos"])

df_nodes_normalised = copy.deepcopy(df_nodes)
df_nodes_normalised["xpos"] = [(xpos - x_min) / (x_max - x_min) for xpos in df_nodes["xpos"]]
df_nodes_normalised["ypos"] = [(ypos - y_min) / (y_max - y_min) for ypos in df_nodes["ypos"]]
display(df_nodes_normalised)
display(df_nodes_normalised[df_nodes_normalised["entry"] == 1])
print(max(df_nodes_normalised["xpos"]))

            id      xpos      ypos  sp_id  entry
0        n_id0  0.242502  0.898506     -1      1
1        n_id1  0.246946  0.896615     -1     -1
2        n_id2  0.249350  0.895178     -1     -1
3        n_id3  0.257189  0.890937     -1     -1
4        n_id4  0.264713  0.887037     -1     -1
...        ...       ...       ...    ...    ...
4505  n_id4505  0.097159  0.853256     -1     -1
4506  n_id4506  0.098204  0.853495     -1     -1
4507  n_id4507  0.099563  0.853495     -1     -1
4508  n_id4508  0.100190  0.853461     -1     -1
4509  n_id4509  0.102333  0.852606     -1     -1

[4510 rows x 5 columns]

            id      xpos      ypos  sp_id  entry
0        n_id0  0.242502  0.898506     -1      1
9        n_id9  0.291459  0.868815     -1      1
25      n_id25  0.320490  0.881508     -1      1
26      n_id26  0.315999  0.927570     -1      1
78      n_id78  0.348448  0.968135     -1      1
301    n_id301  0.103345  0.852207     -1      1
1721  n_id1721  0.543812  0.907921     -1      1
2723  n_id2723  0.969743  0.243430     -1      1
2724  n_id2724  0.939531  0.247419     -1      1
3313  n_id3313  0.761734  0.056871     -1      1
4449  n_id4449  0.883335  0.248324     -1      1
4489  n_id4489  0.075504  0.844730     -1      1

0.9941173024612256

# Save CSVs

In [24]:
df_nodes_normalised.to_csv(f"{python_directory}/node_list.csv", index=False)
df_links.to_csv(f"{python_directory}/link_list.csv", index=False)

df = df_links
display(df[df["start"] == df["end"]])

display(df_nodes_normalised[df_nodes_normalised["id"] == "n_id258"])

Empty DataFrame
Columns: [id, start, end, maxspeed]
Index: []

          id      xpos      ypos  sp_id  entry
258  n_id258  0.093077  0.716507     -1     -1